morse-firmware-sign: (APP-6014, PR #346) allow maintaining no enforcement
Previously, if you upgraded signing enforcement was turned back
on. This is annoying for test setups.


Approved-by: Prabha Murugesan
Approved-by: Lyall Beveridge

diff --git a/features/morse-firmware-sign/files/etc/uci-defaults/99-enforce-fw-sign b/features/morse-firmware-sign/files/etc/uci-defaults/99-enforce-fw-sign
--- a/features/morse-firmware-sign/files/etc/uci-defaults/99-enforce-fw-sign
+++ b/features/morse-firmware-sign/files/etc/uci-defaults/99-enforce-fw-sign
@@ -1,6 +1,13 @@
 #!/bin/sh
-# Force firmware signature enforcement on first boot
 
-uci set system.@system[0].enforce_fw_sign='1'
+# Default to enforcing firmware signing.
+# If this is unset, unsigned images will be allowed without
+# error (NB: signed images will still fail!).
+# Note that this config option is a new one introduced by
+# this package, and is not supported by the standard OpenWrt
+# signature check.
+if ! uci -q get system.@system[0].enforce_fw_sign; then
+	uci set system.@system[0].enforce_fw_sign='1'
+fi
 
 exit 0
